require 'jekyll/template_wrapper/version'
require 'jekyll/template_wrapper/buffer'
require 'jekyll/template_wrapper/convertible_patch'
require 'jekyll/template_wrapper/haml_tag'
require 'jekyll/template_wrapper/include_tag_patch'
